services:
  app:
    image: ghcr.io/ximeraproject/xake2024:medium_a   
    volumes:
      # This is where VS Code should expect to find your project's source code and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      - ..:/code:cached
    #   - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"   # run forever
    # environment:
    #   - NODE_ENV=development
    # ports:
    #   - "3000:3000"  # Expose app's port (your Node.js app port)
    network_mode: service:ximeraserver
  ximeraserver:
    image: registry.gitlab.kuleuven.be/wet/ximera/ximeradocker:2.3_b
    ports:
      - "2080:2000"          # Expose Ximera on port 2080
    # volumes:
    #   - ./nginx:/etc/nginx/conf.d  # Nginx configuration files or static files
#     networks:
#       - devnet             # Custom network for container communication
# networks:
#   devnet:
#     driver: bridge
